[ #1088 ] - keep/delete original files
WPChill/modula-lite pull request #1095
Opened 2024-10-08 07:35 UTC by razvanaldea89

2024-10-09 08:09 UTC, cristeacosmin requested changes

2024-10-09 08:09 UTC, cristeacosmin commented on includes/admin/class-modula-gallery-upload.php
> +			if ( is_wp_error( $attachment_id ) ) {
aici faci handle la eroare

2024-10-09 08:09 UTC, cristeacosmin commented on includes/admin/class-modula-gallery-upload.php
> +			);
aici nu mai faci handle la eroare

2024-10-09 08:09 UTC, cristeacosmin commented on assets/js/admin/modula-gallery-upload.js
> +						'.modula_file_browser input[type="checkbox"]:checked'
inputu ala are un id, de ce nu-l folosesti pe ala? document.getElementById(delete_files) ?

2024-10-10 07:44 UTC, razvanaldea89 commented on includes/admin/class-modula-gallery-upload.php
> +			);
Are fix aici: 94ff4ac5407c095eff8eabd1ff4af4a0eaf5b2a7

2024-10-10 07:45 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +						'.modula_file_browser input[type="checkbox"]:checked'
Nu e input-ul pentru delete_files ci sunt path-urile selectate

2024-10-10 11:32 UTC, cristeacosmin approved these changes

2024-10-10 11:46 UTC, merged