[ #1049 ] - modal design
WPChill/modula-lite pull request #1096
Opened 2024-10-08 11:20 UTC by razvanaldea89

2024-10-09 08:16 UTC, cristeacosmin requested changes

2024-10-09 08:16 UTC, cristeacosmin commented on assets/js/admin/modula-gallery-upload.js
> +		const foldersCheckboxes = document.querySelectorAll(
aici asta pare super dubios facut - uite un approach mai bun. codu nu-i testat e scris la graba
```suggestion
const modulaFileBrowser = document.querySelector('.modula_file_browser');

if (modulaFileBrowser) {
    modulaFileBrowser.addEventListener('change', function(event) {
        if (event.target.matches('input[type="checkbox"]')) {
            updateSendButtonState();
        }
    });
}

function updateSendButtonState() {
    const checkedCheckboxes = modulaFileBrowser.querySelectorAll('input[type="checkbox"]:checked');
    modulaSendFoldersButton.classList.toggle('disabled', checkedCheckboxes.length === 0);
}

// Initial button state
updateSendButtonState();
```

2024-10-10 08:06 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +		const foldersCheckboxes = document.querySelectorAll(
Are commit aici: b59988a123900ab4351e70ad66b521da560ee3e3

2024-10-10 11:32 UTC, cristeacosmin approved these changes

2024-10-10 11:47 UTC, merged