[ #1070 ] - create folder for zip uploads
WPChill/modula-lite pull request #1100
Opened 2024-10-09 07:50 UTC by razvanaldea89

2024-10-09 08:18 UTC, cristeacosmin requested changes

2024-10-09 08:18 UTC, cristeacosmin commented on includes/admin/class-modula-gallery-upload.php
> +			$pathdata['path']   = $pathdata['path'] . '/modula_zip_upload';
ce se intampla daca apare alt zip fara subdir ? ma gandesc ca asta e cazul cand nu este un folder zip-uit ci cand sunt arhivate direct X elemente.

cred ca ar trebui un timestamp acolo pentru a nu fi acelasi folder tot timpul

2024-10-10 08:16 UTC, razvanaldea89 commented on includes/admin/class-modula-gallery-upload.php
> +			$pathdata['path']   = $pathdata['path'] . '/modula_zip_upload';
Mereu se creeaza un folder cu numele fisierului .zip, precum si an si luna. E in forma uploads/modula_zip_upload/2024/10/nume_fisier/fisiere din zip. daca exista fisierul zip, numele noului fisier zip uploadad se schimba, si la fel se schimba si numele folderului final.

2024-10-10 11:33 UTC, cristeacosmin commented on includes/admin/class-modula-gallery-upload.php
> +			$pathdata['path']   = $pathdata['path'] . '/modula_zip_upload';
dar daca uploadurile sunt in aceeasi zi?

2024-10-10 11:52 UTC, razvanaldea89 commented on includes/admin/class-modula-gallery-upload.php
> +			$pathdata['path']   = $pathdata['path'] . '/modula_zip_upload';
facut aici: c57d3f79be71c712fff6edb97ede6ce3e7202b88

2024-10-11 10:27 UTC, cristeacosmin approved these changes

2024-10-11 10:52 UTC, merged