[ #1053 ] - file upload process
WPChill/modula-lite pull request #1102
Opened 2024-10-09 07:55 UTC by razvanaldea89

2024-10-09 08:21 UTC, cristeacosmin requested changes

2024-10-09 08:21 UTC, cristeacosmin commented on assets/js/admin/modula-gallery-upload.js
> +var $ = jQuery;
nu-i bine, ori folosesti jQuery - ori faci self calling function pentru a limita scope-ul. rescrierea $ e bad practice

2024-10-09 08:30 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +var $ = jQuery;
Yup, am copiat si am facut asa ca sa nu imi mai tot urle erorile :D e in curs de modificare

2024-10-10 11:57 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +var $ = jQuery;
am modificat https://github.com/WPChill/modula-lite/pull/1109/files

2024-10-11 10:58 UTC, cristeacosmin approved these changes

2024-10-11 10:59 UTC, merged