1072 task 24 create upload process progress maybe
WPChill/modula-lite pull request #1116
Opened 2024-10-11 06:23 UTC by razvanaldea89

2024-10-11 10:31 UTC, cristeacosmin requested changes

2024-10-11 10:31 UTC, cristeacosmin commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
de ce e progressClass si nu progressBar? numele e ambiguu

2024-10-11 10:41 UTC, razvanaldea89 commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
E vorba de o clasa separata din script, ce se ocupa de progress display

2024-10-11 10:57 UTC, cristeacosmin commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
pai da, dar clasa se numeste ModulaProgressBar, adica instanta ar trebui sa fie (modula)progressBar, nu? am pus in paranteza prefixul ca nu e nevoie

2024-10-11 11:01 UTC, razvanaldea89 commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
mai avem un progressBar, care defineste altceva, si incepem sa ne incurcam. O sa modific numele clasei.

2024-10-11 11:02 UTC, razvanaldea89 commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
e7202bbca866736ae89b86a7713700488c19f664

2024-10-23 10:40 UTC, razvanaldea89 commented on assets/js/admin/wp-modula-upload.js
> +		progressClass: false,
https://github.com/WPChill/modula-lite/commit/214c0d7b2ce52cddcf12353b955b01d737d5a6d7

2024-10-23 10:40 UTC, cristeacosmin approved these changes

2024-10-23 10:41 UTC, merged