[ #1114 ] - recursive folder scan
WPChill/modula-lite pull request #1117
Opened 2024-10-11 10:07 UTC by razvanaldea89

2024-10-11 10:31 UTC, cristeacosmin approved these changes

2024-10-11 12:17 UTC, cristeacosmin requested changes

2024-10-11 12:17 UTC, cristeacosmin commented on assets/js/admin/modula-gallery-upload.js
> +class ModulaProgressClass {
problema nu era cum era denumita clasa, ci cum era denumita proprietatea in cealalta clasa. Asta era pus corect ModulaProgressBar ... in php nu adaugi in numele clasei sufixul class, nu?

2024-10-11 12:21 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +class ModulaProgressClass {
mai avem un progressBar in cealalta clasa, de care depind mai multe, asta fiind motivul pentru care am modificat numele clasei

2024-10-11 12:23 UTC, cristeacosmin commented on assets/js/admin/modula-gallery-upload.js
> +class ModulaProgressClass {
pai atunci asta ar trn sa fie class ModulaGalleryUpload ..

2024-10-11 12:29 UTC, razvanaldea89 commented on assets/js/admin/modula-gallery-upload.js
> +class ModulaProgressClass {
ModulaGalleryUpload e cealalta clasa, ce se ocupa de upload. Asta e cea care se ocupa de progress bar. o sa o pun intr-un fisier separat

2024-10-23 11:14 UTC, cristeacosmin approved these changes

2024-10-23 11:29 UTC, merged