2.11.3
WPChill/modula-lite pull request #1145
Opened 2024-11-20 15:10 UTC by razvanaldea89

2024-11-21 11:33 UTC, cristeacosmin approved these changes

2024-11-21 13:55 UTC, cristeacosmin requested changes

2024-11-21 13:55 UTC, cristeacosmin commented on assets/js/admin/wp-modula-gutenberg.js
> +      if (idCheck != id || undefined == settings) {
!== , ===

2024-11-21 13:55 UTC, cristeacosmin commented on assets/src/js/components/edit.js
> +			if (idCheck != id || undefined == settings) {
!==, ===

2024-11-21 13:55 UTC, cristeacosmin commented on includes/class-modula-gutenberg.php
> +		add_filter( 'rest_prepare_modula-gallery', array( $this, 'rest_api_filter_data' ), 15, 3 );
vezi ca ai callbackul pentru fieldul respectiv, de ce ai nevoie sa modifici tot raspunsul?

2024-11-21 13:55 UTC, cristeacosmin commented on includes/class-modula-gutenberg.php
> +			return $response;
doar daca e slider e nevoie de functionalitatea asta? daca e o galerie care are un video - tot are nevoie de thumb

2024-11-21 14:00 UTC, razvanaldea89 commented on includes/class-modula-gutenberg.php
> +			return $response;
🤦🏼  am copiat de la slider, partea aia trebuie sa o scot

2024-11-22 11:03 UTC, cristeacosmin approved these changes

2024-11-27 11:37 UTC, merged